version: '3'

tasks:
  docker:up:
    cmds:
      - docker compose up --build

  db:reset:
    desc: Reset the admin-service database (drop and migrate tables)
    dir: shared/cmd/db-reset
    cmds:
      - go run main.go